### ISSUE TITLE
issue with the stl file for the 3D printed motor housing

### ISSUE THREAD

**Issue by bamouroux** [ries-lab/LaserEngine#1]
Hello,
Thank you for this nice description on how to build such an agitation box =)
However I am facing an issue with the stl file for the 3D printed motor housing (for mortor v2):
It appears that the file has to be repaired before being able to print it.
I can do it with software such as Autodesk or Blender. But when I open the stl file with such a software it changes the scale of the object... 51m of length O:
Is it possible to provide an other repaired file, or just to give the length of the object (in inches or meters) so I can repair it on my own and rescale it?
Thank you in advance

**Comment by jdeschamps** [comment]
Hi!
I also see this with SolidWorks. Basically the software interprets the unit as meters, instead of mm. So you need to scale it down by 1000.

Now, we use Cura to 3D print and in this software the piece is shown at 52*50*50 mm (values from the top of my head, I don't have access to the computer now). Which software reports "file to be repaired" error? Or is this just related to the wrong unit?

Next week I can try to play around with this.

**Comment by bamouroux** [comment]
Hi !
Ok I will rescale it.
Concerning the issue, when I opened it in a fablab (I don't know which software), the object appears as an overlap of different elements which are not unified together. It seems that there are a lot of "vacuum defect" where there are changes of shape or thickness. As a result the fablab facility refused to print it, claming that this is not a stable object.

**Comment by jdeschamps** [comment]
Hi! 
Without their software I can't really test what is wrong, since we manage to print it fine on our 3D printer... Next time you pass by there, maybe you can inquire on the software they use?

Nonetheless, I just added a .3mf file in the same folder. Using solidworks, this file seems to not have the scaling problem observed earlier.

Let me know if things work out for you.

**Comment by bamouroux** [comment]
Hi!
Sorry for my late answer, I was waiting for the last component (long delay to get delivered the rolling ball) to assemble the box with the new version of the housing motor's file you provide.
Regarding to the new file you provide I found good points and sources of improvements.
At first, this new file solves the main problems I found with the first one.
- the new file does not show lot of errors. It could be solved by the software used at the fablab (sorry I forgot to ask the name of it).
- the scaling issue is fixed, the object is directly 50.9x50.9x52 if I remember.
However I faced 2 major issues:
     -The middle hole for the rolling ball is just too small to allow it to go in. Therefore the housing motor is not long enough. I think an idea should be to increase the diameter of this hole from 0.5 cm that will allow the user to place it more easily. If it move a little it is not a big deal.
     -The 4 holes for the M3 screws are too big (3cm vs 2.5cm diameter for M3 screws)
 A final suggestion should be to provide the file to print the housing motor in ".stl" format which is the one mainly used by 3D printed software, or to advice a free software able to convert ".3mf" to the ".stl" format.

**Comment by jdeschamps** [comment]
Thanks for the feedback!

>   -The middle hole for the rolling ball is just too small to allow it to go in. Therefore the housing motor is not long enough. I think an idea should be to increase the diameter of this hole from 0.5 cm that will allow the user to place it more easily. If it move a little it is not a big deal.

Actually that's by design, the person who designed it wanted it tight. So we usually hammer it in. :)
Maybe I should add a note in the description.

>   -The 4 holes for the M3 screws are too big (3cm vs 2.5cm diameter for M3 screws)

On the 3mf files I measure 3 mm holes, as well as on our 3D printed left overs. Where did you observe the 2.5 mm ? On the file or on your printed piece?

As far as I know we did not have problems screwing in small M3 screws in those holes on different pieces.

>   A final suggestion should be to provide the file to print the housing motor in ".stl" format which is the one mainly used by 3D printed software, or to advice a free software able to convert ".3mf" to the ".stl" format.

I agree, unfortunately if I export the .3mf with Solidworks to .stl, then I end up again with the problem you observed: a 50 m tall model...  I will try with another software.

Unfortunately it was designed as meshes directly, I would have a CAD file things would be easier to scale/modify/export.

**Comment by bamouroux** [comment]
Thank you for your answers, I will answer to the points you mentionned:
-Ok, I like the hammer solution =). I was scared to do it ^^
-I observed the 2.5mm holes on the final printed piece. I don't know why as I did not modified your file, just converted it to .stl with a software found online (nchsoftware - convert 3D  meshes).
-For the scaling I think it is no a big problem. Knowing the real dimensions of you object is enough to rescale it (in 1s) at any 3D-printing facility. 
Based on your model, I designed a similar object with "Autodesk Inventor" and I face the same scaling issue.

**Comment by jdeschamps** [comment]
Interestingly enough, it turns out STL files do not contain any scale information. So the fault resides in the software that imports them ([source wikipedia](https://en.wikipedia.org/wiki/STL_(file_format)#cite_note-7)).

I updated the designs with a better version, including this time the STEP files. So that anyone can export the STL files from them!

I consider this issue closed, let me know if you feel differently. :)
